apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app  # 定义 selector
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app  # 必须与 selector.matchLabels 一致
    spec:
      containers:
      - name: app
        image: <IMAGE_URL>:<IMAGE_TAG>  # 占位符，将在Pipeline中替换
        ports:
        - containerPort: 8080
