apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{appName}}
  labels:
    app: {{appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{appName}}
  template:
    metadata:
      labels:
        app: {{appName}}
        version: v1
    spec:
      containers:
        - name: {{appName}}
          # 指定SWR中的镜像地址
          image: {{repositoryUrl}}/{{orgName}}/{{imageName}}:{{tagVersion}}
          ports:
            - containerPort: {{serverPort}}
          # 声明Pod的资源（Request和Limit）请根据应用的实际需求修改
          resources:
            requests:
              memory: {{requestsMemory}}
              cpu: {{requestsCpu}}
            limits:
              memory: {{limitsMemory}}
              cpu: {{limitsCpu}}
      imagePullSecrets:
        - name: default-secret
